version: "3.5"
services:

  nginx-pi:
    image: nginx-pi
    build:
      context: ./pi-dashboard
    container_name: nginx-pi
    ports:
      - 80:80
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/hdd/config/portainer_data:/data
    ports:
      - 8000:8000
      - 9000:9000
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - WEBUI_PORT=8090
    volumes:
      - /mnt/hdd/config/qbittorrent_config:/config
      - /mnt/hdd/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8090:8090
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl=http://pi:8096
    user: 1000:1000    
    volumes:
      - /mnt/hdd/config/jellyfin_config:/config
      - /mnt/hdd/config/jellyfin_cache:/cache
      - /mnt/hdd/media:/media    
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900/udp
      - 7359:7359/udp
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    volumes:
      - /mnt/hdd:/srv
      - /mnt/hdd/config/filebrowser.db:/database.db
    ports:
      - 8100:80
    restart: unless-stopped

